version: '3.3'

services:
  bot:
    image: "${DOCKER_BOT_IMAGE_NAME}"
    container_name: "${DOCKER_BOT_CONTAINER_NAME}"
    stop_signal: SIGINT
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        DOCKER_BOT_FOLDER_NAME: "${DOCKER_BOT_FOLDER_NAME}"
    working_dir: "/usr/src/app/${DOCKER_BOT_FOLDER_NAME}"
    volumes:
      - db_data:/usr/src/app/${DOCKER_BOT_FOLDER_NAME}/data
    command: python3 main.py
    restart: always
    environment:
      - DOCKER_BOT_FOLDER_NAME=${DOCKER_BOT_FOLDER_NAME}
    env_file:
      - ".env"
    networks:
      - tg_bot
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # Uncomment if you use Redis
    # depends_on:
    #   - redis_cache

  # Uncomment if you use Redis
  # redis_cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   command: redis-server --port $REDIS_PORT --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
  #   env_file:
  #     - ".env"
  #   volumes:
  #     - cache:/data
  #   networks:
  #     - tg_bot

networks:
  tg_bot:
    driver: bridge

volumes:
  db_data:
  # Uncommented if you use Redis
  # cache: